services:
  app:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: predictive-hdd-failure-api
    restart: unless-stopped
    ports:
      - "8000:8000"
    environment:
      - PYTHONUNBUFFERED=1
    volumes:
      - ./artifacts:/app/artifacts
      - ./mlruns:/app/mlruns
      # If a local logs folder is used, uncomment the next line:
      # - ./logs:/app/logs
